@startuml RVMS
left to right direction
actor Patient as patient
actor HCP as hcp

rectangle App {
    usecase "Log In" as LogIn
    usecase "Acquire Device Data" as AcquireDeviceData
    usecase "See Own Graphs" as SeeOwnGraphs
    usecase "See Patients' Graphs" as SeePatientsGraphs
    usecase "Add HCP" as AddDoctor
    usecase "Remove HCP" as RemoveDoctor
    usecase "Remove Patient" as RemovePatient
}

rectangle Device {
    usecase "Charge" as ChargeDevice
    usecase "Wear" as WearDevice
    usecase "Sync" as SyncDevice
}

patient --> LogIn
patient --> AcquireDeviceData
patient --> SeeOwnGraphs
patient --> AddDoctor
patient --> RemoveDoctor

hcp --> LogIn
hcp --> SeePatientsGraphs
hcp --> RemovePatient

ChargeDevice <-- patient
WearDevice <-- patient
SyncDevice <-- patient

@enduml
